version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_production_db_name
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    image: tms
    # Remove the volume mapping to prevent overriding /app
    # volumes:
    #   - .:/app
    # Remove the port mapping to prevent port clashes
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
